added hamburger menu in template 3
shelcia/dynamic-portfolio pull request #320
Opened 2024-01-11 18:13 UTC by rishabhguptajs

# Description

I've added the hamburger icon and menu in mobile view of template 3.

Fixed Issue - #210 

Test 1 - 

<img width="629" alt="commit-1" src="https://github.com/shelcia/dynamic-portfolio/assets/48509043/af95306f-b7ae-4ee3-be2e-94228dff54e5">

Test 2 (When opening the hamburger menu by clicking on that icon) - 

<img width="622" alt="commit-2" src="https://github.com/shelcia/dynamic-portfolio/assets/48509043/407ef01e-027b-46ca-a044-8ed01961f74d">

2024-01-12 01:08 UTC, shelcia requested changes
try using responsive navbar component from bootstrap instead of window listeners

2024-01-12 03:48 UTC, rishabhguptajs commented
okay

2024-01-12 04:03 UTC, rishabhguptajs commented
I've made the required checks, can you please check and review it?

2024-01-13 18:57 UTC, shelcia approved these changes

2024-01-13 18:57 UTC, merged